### ISSUE TITLE
Using AMQP instead of python queues

### ISSUE THREAD

**Issue by azet** [zhaozhang/amfora#2]
Hi AMFORA Team,

A short question/recommendation:

I've just watched your Talk at SC13 and read through the code. Is there a reason why AMQP is not used for queues - This would also eliminate some fault-tolerance issues that were mentioned during the Q&A.

Thanks for your time.

**Comment by zhaozhang** [comment]
Hi Aaron,

AMFORA started as a thesis research project, so I focused on the
prototyping of the system. I will definitely look into AMQP. Thanks for the
suggestion!

Best
Zhao

2013/11/20 Aaron Zauner notifications@github.com

**Comment by azet** [comment]
Sounds good, thanks. Good project!
